In [1]:
from nltk import stem
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from sklearn.model_selection import train_test_split
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df = pd.read_csv(r'C:/Users/User/rating analysis/7817_1.csv')

In [3]:
df1 = df[['reviews.rating','reviews.text']]

In [4]:
df1.isnull().sum()

reviews.rating    420
reviews.text        0
dtype: int64

In [26]:
df1['reviews.text'][3]

'bought one first paperwhit pleas constant companion suppos ive read average book everi three day past howev mani year it wouldnt give youd pri cold dead fingersfor sundri logist reasons ive also made good use amazon kindl app iphone paperwhit screen naturally cool usabl delivers work well attract companion kindleof course aspect paperwhit would like critique ah knew come somewhere didnt youa member bookbub get daili list alert book deal chosen genres take mani them however ive found that even best world cant keep up day seem everi book read ive bought two there much good stuff there accumul effect number book actual paperwhit creep ever upward time with mind ive notic pageturn remain exact same everi action kindl becom posit glacial slow slow think malfunctioning general consensus appear expect one mani book download onto kindle begin behav flakey manner drive mad amazon state hold thousand books believ them figur would need second paperwhit read im wait action complet first oneread'

In [6]:
df1.dropna(subset=["reviews.rating","reviews.text"],how = "any",inplace=True)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [7]:
df1.isnull().sum()

reviews.rating    0
reviews.text      0
dtype: int64

In [8]:
df1['reviews.rating'].value_counts()

5.0    741
4.0    236
3.0    124
1.0     42
2.0     34
Name: reviews.rating, dtype: int64

In [9]:
df1.shape

(1177, 2)

In [10]:
stemmer = stem.SnowballStemmer('english')
stopwords = set(stopwords.words('english'))

def alternative_review_messages(msg):
    # converting messages to lowercase
    msg = msg.lower()
    # removing stopwords
    msg = [word for word in msg.split() if word not in stopwords]
    # using a stemmer
    msg = " ".join([stemmer.stem(word) for word in msg])
    return msg

In [11]:
df1["reviews.text"] = df1['reviews.text'].apply(alternative_review_messages)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [12]:
df1["reviews.text"]

0       initi troubl decid paperwhit voyag review less...
1       allow prefac littl history. (was) casual reade...
2       enjoy far. great reading. origin fire sinc 201...
3       bought one first paperwhit pleas constant comp...
4       say upfront - like coroporate, hermet close st...
                              ...                        
1592    remot got alexa-echo control volume.... think ...
1593    chang batteri remot twice per month sinc purch...
1594    remot activate, connect box.a poor design remo...
1595    job super priced. feel like offer replac remot...
1596    order item replac one longer works. direct new...
Name: reviews.text, Length: 1177, dtype: object

In [13]:
df1["reviews.text"] = df1["reviews.text"].str.replace(r'\d+','')
df1["reviews.text"] = df1["reviews.text"].str.replace(r'\s+',' ')
df1["reviews.text"] = df1["reviews.text"].str.replace(r'\[[0-9]*\]',' ')

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Data

In [14]:
import string
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

In [15]:
df1["reviews.text"] = df1['reviews.text'].apply(remove_punctuations)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [16]:
df1["reviews.text"].head()

0    initi troubl decid paperwhit voyag review less...
1    allow prefac littl history was casual reader o...
2    enjoy far great reading origin fire sinc  fire...
3    bought one first paperwhit pleas constant comp...
4    say upfront  like coroporate hermet close stuf...
Name: reviews.text, dtype: object

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df1["reviews.text"], df1["reviews.rating"], test_size = 0.25, random_state = 37)

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vt = TfidfVectorizer(vocabulary=None,tokenizer=None)
X_vt = tfidf_vt.fit_transform(X_train)

In [19]:
X_vt1 = tfidf_vt.transform(X_test)

In [20]:
X_vt.shape

(882, 5155)

In [21]:
y_train.shape

(882,)

In [22]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_vt, y_train)
# Predicting the Test set results
y_pred = classifier.predict(X_vt1)
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print('\n')
print(classification_report(y_test, y_pred))

[[  1   0   0   0   6]
 [  0   3   0   0   5]
 [  0   1  10   1  14]
 [  2   1   0   8  49]
 [  0   2   1   6 185]]


              precision    recall  f1-score   support

         1.0       0.33      0.14      0.20         7
         2.0       0.43      0.38      0.40         8
         3.0       0.91      0.38      0.54        26
         4.0       0.53      0.13      0.21        60
         5.0       0.71      0.95      0.82       194

    accuracy                           0.70       295
   macro avg       0.58      0.40      0.43       295
weighted avg       0.68      0.70      0.64       295



In [ ]:
classifier.score(X_vt1,y_test)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

rfc=RandomForestClassifier(random_state=42)
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X_vt, y_train)

In [ ]:
CV_rfc.best_params_

In [ ]:
CV_rfc.best_score_

In [ ]:
a = input("enter the product review")
data = {'Text':[a]}
df1 = pd.DataFrame(data)
df1["Text"] = df1["Text"].str.replace(r'\d+','')
df1["Text"] = df1["Text"].str.replace(r'\s+',' ')
df1["Text"] = df1["Text"].str.replace(r'\[[0-9]*\]',' ')
df1["Text"] = df1['Text'].apply(remove_punctuations)

vec = tfidf_vt.transform(df1["Text"])

Rating = CV_rfc.predict(vec)
print("The product is {}".format(Rating))

In [ ]:
import pickle
pickle_file = 'Rating.pkl'
with open(pickle_file,'wb')  as file:
    pickle.dump(CV_rfc,file)

In [ ]:
df1["reviews.text"][0]

In [ ]:
df1["reviews.text"][1]

In [27]:
import pickle
pickle_file = 'Rating_t.pkl'
with open(pickle_file,'wb')  as file:
    pickle.dump(tfidf_vt,file)